services:
  # ==== Serviço da API ====
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: budget-agent
    restart: unless-stopped
    command: uvicorn main:app --host 0.0.0.0 --port 8001 --reload
    volumes:
      - .:/app
    ports:
      - "8001:8001"